language: python
sudo: required
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
env:
  - TZ=Europe/Kiev
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==7.0 flake8
  - python2 bootstrap.py
install:
  - bin/buildout -N
script:
  - flake8 --config .flake8
  - bin/nosetests
after_success:
  - bin/coveralls
